version: '3.8'

x-user: &user-ext
  build:
    context: .
  restart: always
  environment:
    LOG_LEVEL: DEBUG
    APP_NAME: peatio
    GRPC_HOST: 0.0.0.0
    GRPC_PORT: 9090
    HTTP_HOST: 0.0.0.0
    HTTP_PORT: 8080
    MONGODB_HOST: mongodb
    MONGODB_DATABASE: user_development
    EVENTSTORE_HOST: mongodb
    EVENTSTORE_DATABASE: eventstore_user
    EVENTBUS_HOST: nats:4222



services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:password@mongodb:27017/

  nats:
    image: nats:2
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222

  user-server:
    << : *user-ext
    command: ./user-server

  user-client:
    << : *user-ext
    ports:
      - "8080:8080"
      - "9090:9090"
    command: ./user-client

volumes:
  postgres-data:
  mongodb-data:
