// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/zsmartex/pkg/v3/infrastucture/database"
	"github.com/zsmartex/pkg/v3/infrastucture/redis"
	"github.com/zsmartex/zsmartex/cmd/users/config"
	"github.com/zsmartex/zsmartex/internal/users/app/router"
	"github.com/zsmartex/zsmartex/internal/users/infras/repo"
	"github.com/zsmartex/zsmartex/internal/users/usecases/users"
	"github.com/zsmartex/zsmartex/pkg/session"
	"google.golang.org/grpc"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, grpcServer *grpc.Server, redisClient *redis.RedisClient) (*App, error) {
	store := session.NewStore(redisClient)
	db, err := postgresFunc(cfg)
	if err != nil {
		return nil, err
	}
	userServiceServer := router.NewUserGRPCServer(grpcServer, store)
	app := New(cfg, userServiceServer)
	return app, nil
}

// wire.go:
