// Code generated by protoc-gen-go-enums. DO NOT EDIT.
// source: common/code/v1/code.proto

package codev1

const (
	email = CodeType_email
	phone = CodeType_phone
)

const (
	login    = CodeCategory_login
	register = CodeCategory_register
)
