// Code generated by protoc-gen-go-enums. DO NOT EDIT.
// source: common/code/v1/code.proto

package codev1

const (
	CODE_TYPE_LOGIN    = CodeType_CODE_TYPE_LOGIN
	CODE_TYPE_REGISTER = CodeType_CODE_TYPE_REGISTER
)

const (
	CODE_CATEGORY_LOGIN    = CodeCategory_CODE_CATEGORY_LOGIN
	CODE_CATEGORY_REGISTER = CodeCategory_CODE_CATEGORY_REGISTER
)
