app:
  name: 'user-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5001

logger:
  log_level: 'debug'

codes_client:
  url: 127.0.0.1:5002

postgres:
  host: localhost
  port: 5432
  user: root
  password: changeme
  database: zsmartex

redis:
  uri: redis://localhost:6379

mongo:
  url: mongodb://root:changeme@127.0.0.1:27017/

nats:
  url: localhost:8222
