app:
  name: 'user-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5001

logger:
  log_level: 'debug'

postgres:
  host: localhost
  port: 5432
  user: root
  password: changeme
  database: zsmartex

redis:
  url: redis://localhost:6379
