// Code generated by protoc-gen-go-enums. DO NOT EDIT.
// source: common/user/v1/user.proto

package userv1

const (
	member     = UserRole_member
	admin      = UserRole_admin
	superadmin = UserRole_superadmin
)

const (
	pending = UserState_pending
	active  = UserState_active
	deleted = UserState_deleted
	banned  = UserState_banned
	locked  = UserState_locked
)
