// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Code is the predicate function for code builders.
type Code func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
